name: "🧪Update GitLab's Future-Service GTFS🚌"
run-name: 🧪Update GitLab's Future-Service GTFS🚌
on:
  push:
    branches: [ main ]
    paths:
      - future-service/**.zip
  workflow_dispatch:

jobs:
  validating-gtfs-and-commit-to-gitlab:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: false

    - name: Push future service to Gitlab
      run: |
        echo Starting to push repo to gitlab
        mkdir temp
        cd temp
        git clone -b future-service "https://oauth2:${token}@gitlab.com/LACMTA/gtfs-bus-dev.git"
        cd ..
        cp -r future-service temp/gtfs-bus-dev/
        git pull
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git config pull.rebase true
        git lfs fetch --all
        git config lfs.https://gitlab.com/LACMTA/gtfs-bus-dev.git/info/lfs.locksverify true
        git remote add gitlab "https://oauth2:${token}@gitlab.com/LACMTA/gtfs-bus-dev.git"
        git add future-service
        git commit -am "🧪[Auto] - Updated on ${{ steps.date.outputs.date }}"
        git pull
        git push gitlab main
      env: 
        token: ${{ secrets.LACMTA_GITLAB_ACCESS_TOKEN }}