name: "🧪Update GitLab's Future-Service GTFS🚌"
run-name: 🧪Update GitLab's Future-Service GTFS🚌
on:
  push:
    branches: [ main ]
    paths:
      - future-service/**.zip
  workflow_dispatch:

jobs:
  validating-gtfs-and-commit-to-gitlab:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: false

    - name: Push future service to Gitlab
      run: |
        echo ***** STARTING PUSH TO GITLAB REPO *****
        mkdir temp
        git -C temp clone --depth 1 --branch future-service https://oauth2:${TOKEN}@gitlab.com/LACMTA/${GITLAB_REPO}.git
        echo ***** CLONED future-service BRANCH INTO temp/future-service *****
        git lfs fetch --all
        cp future-service/. temp/${GITLAB_REPO}
        echo ***** COPIED future-service DIRECTORY CONTENT *****
        cd temp/${GITLAB_REPO}
        echo ***** FILES: *****
        ls
        git pull
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git config pull.rebase true        
        git config lfs.https://gitlab.com/LACMTA/${GITLAB_REPO}.git/info/lfs.locksverify true
        git add .
        git commit -am "🧪[Auto] - Updated on ${{ steps.date.outputs.date }}"
        echo ***** CHANGES COMMITTED *****
        git push origin future-service
        echo ***** PUSHED TO GITLAB *****
        echo :tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:
      env: 
        TOKEN: ${{ secrets.LACMTA_GITLAB_ACCESS_TOKEN }}
        GITLAB_REPO: gtfs_bus
