name: "🧪Update GitLab's Future-Service GTFS🚌"
run-name: 🧪Update GitLab's Future-Service GTFS🚌
on:
  push:
    branches: [ main ]
    paths:
      - future-service/**.zip
  workflow_dispatch:

jobs:
  validating-gtfs-and-commit-to-gitlab:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: false

    - name: Push future service to Gitlab
      run: |
        echo Starting to push repo to gitlab
        mkdir temp
        git -C temp clone --depth 1 --branch future-service https://oauth2:${token}@gitlab.com/LACMTA/gtfs-bus-dev.git
        echo cloned future-service branch into temp/future-service
        git lfs fetch --all
        cp -r future-service temp/gtfs-bus-dev
        echo copied future-service directory content
        cd temp/gtfs-bus-dev
        echo listing files:
        ls
        git pull
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git config pull.rebase true        
        git config lfs.https://gitlab.com/LACMTA/gtfs-bus-dev.git/info/lfs.locksverify true
        git add .
        git commit -am "🧪[Auto] - Updated on ${{ steps.date.outputs.date }}"
        echo changes committed
        git push origin future-service
        echo pushed to gitlab
      env: 
        token: ${{ secrets.LACMTA_GITLAB_ACCESS_TOKEN }}
