name: "Validate GTFS👀🚌"

on:
  push:
    branches: [ main ]
jobs:
  validating-gtfs:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'lacmta'
        repository: 'gtfs_bus'
    - name: Download GTFS Validator
      run: curl "https://lacmta.github.io/gtfs-validator/gtfs-validator.jar" -o "gtfs-validator-cli.jar"
    - name: Validate GTFS
      run: |
        java -jar gtfs-validator-cli.jar -i gtfs_bus/gtfs_bus.zip -o gtfs_bus/output
        cd gtfs_bus
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .      
        git commit -am '[Auto] Output Validated GTFS Results'
        git push https://${{secrets.METRO_GITHUB_TOKEN}}@github.com/lacmta/gtfs_bus.git